/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alias-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias Targets */
        get: operations["core_alias_targets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Alias */
        post: operations["core_create_alias"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dq/unmapped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dq Unmapped */
        get: operations["core_dq_unmapped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["core_findings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["core_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Imports */
        get: operations["core_imports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["core_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modules List */
        get: operations["core_modules_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nav */
        get: operations["core_nav"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Apps */
        get: operations["ops_apps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/apps/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App 360 */
        get: operations["ops_app_360"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention */
        get: operations["ops_attention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/contracts/renewals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renewals */
        get: operations["ops_renewals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["ops_costs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["ops_filters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/licenses/utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Licenses */
        get: operations["ops_licenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["ops_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tickets */
        get: operations["ops_tickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Backlog */
        get: operations["ops_ticket_backlog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets/mttr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Mttr */
        get: operations["ops_ticket_mttr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Sla */
        get: operations["ops_ticket_sla"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Volumes */
        get: operations["ops_ticket_volumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Detail */
        get: operations["ops_ticket_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/vendors/sla-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vendor Sla Trend */
        get: operations["ops_vendor_sla_trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["core_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgingOut */
        AgingOut: {
            /** D0 7 */
            d0_7: number;
            /** D31 90 */
            d31_90: number;
            /** D8 30 */
            d8_30: number;
            /** D90P */
            d90p: number;
        };
        /** AliasIn */
        AliasIn: {
            /** Kind */
            kind: string;
            /** Raw Value */
            raw_value: string;
            /** Target */
            target: string;
        };
        /** AliasOut */
        AliasOut: {
            /** Kind */
            kind: string;
            /** Raw Value */
            raw_value: string;
            /** Reresolved */
            reresolved: {
                [key: string]: number;
            };
            /** Target Id */
            target_id: string;
        };
        /** AliasTarget */
        AliasTarget: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** AliasTargetsOut */
        AliasTargetsOut: {
            /** Items */
            items: components["schemas"]["AliasTarget"][];
        };
        /** App360Out */
        App360Out: {
            app: components["schemas"]["AppRow"];
            /** Changes */
            changes: components["schemas"]["ChangeRow"][];
            /** Contracts */
            contracts: components["schemas"]["RenewalRow"][];
            /** Cost */
            cost: components["schemas"]["CostRow"][];
            /** Docs */
            docs: components["schemas"]["DocRow"][];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Jira */
            jira: components["schemas"]["JiraRow"][];
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Licenses */
            licenses: components["schemas"]["LicenseRow"][];
            /** Open Tickets */
            open_tickets: components["schemas"]["TicketRow"][];
            /** Volumes */
            volumes: components["schemas"]["VolumeRow"][];
        };
        /** AppRow */
        AppRow: {
            /** Annual License Cost Base */
            annual_license_cost_base: number | null;
            /** App Id */
            app_id: string;
            /** Cost Ytd Base */
            cost_ytd_base: number | null;
            /** Criticality */
            criticality: string | null;
            /** Family */
            family: string | null;
            /** Incidents Per Month 3M */
            incidents_per_month_3m: number | null;
            /** License Utilization */
            license_utilization: number | null;
            /** Lifecycle */
            lifecycle: string | null;
            /** Name */
            name: string;
            /** Open Risks */
            open_risks: number;
            /** Primary Vendor */
            primary_vendor: string | null;
            /** Sla Pct 3M */
            sla_pct_3m: number | null;
        };
        /** AppsOut */
        AppsOut: {
            /** Items */
            items: components["schemas"]["AppRow"][];
        };
        /** AttentionOut */
        AttentionOut: {
            /** As Of */
            as_of: string;
            /** By Reason */
            by_reason: {
                [key: string]: number;
            };
            /** Count */
            count: number;
            /** Data As Of Last Import */
            data_as_of_last_import: string | null;
            /** Items */
            items: components["schemas"]["AttentionRow"][];
        };
        /** AttentionRow */
        AttentionRow: {
            /** Age Days */
            age_days: number | null;
            /** App */
            app: string | null;
            /** Assigned To Pid */
            assigned_to_pid: string | null;
            /** Assignment Group */
            assignment_group: string | null;
            /** Number */
            number: string;
            /** Opened At */
            opened_at: string | null;
            /** Priority */
            priority: number | null;
            /** Reasons */
            reasons: string[];
            /** Short Description */
            short_description: string | null;
            /** State */
            state: string | null;
            /** Ticket Id */
            ticket_id: string;
        };
        /** BacklogGroupRow */
        BacklogGroupRow: {
            /** D0 7 */
            d0_7: number;
            /** D31 90 */
            d31_90: number;
            /** D8 30 */
            d8_30: number;
            /** D90P */
            d90p: number;
            /** Group */
            group: string | null;
            /** Total */
            total: number;
        };
        /** BacklogOut */
        BacklogOut: {
            aging: components["schemas"]["AgingOut"];
            /** At */
            at: string;
            /** By Group */
            by_group: components["schemas"]["BacklogGroupRow"][];
            /** Flow */
            flow: components["schemas"]["FlowRow"][];
            /** Stale Excluded */
            stale_excluded: number;
            /** Total */
            total: number;
        };
        /** ChangeRow */
        ChangeRow: {
            /** Change Type */
            change_type: string | null;
            /** Close Code */
            close_code: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Number */
            number: string;
            /** Short Description */
            short_description: string | null;
            /** Start Date */
            start_date: string | null;
        };
        /** CostRow */
        CostRow: {
            /** Actual */
            actual: number | null;
            /** Budget */
            budget: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Variance Pct */
            variance_pct: number | null;
        };
        /** CostsOut */
        CostsOut: {
            /**
             * Group By
             * @enum {string}
             */
            group_by: "app" | "vendor" | "category" | "app_category";
            /** Months */
            months: string[];
            /** Rows */
            rows: components["schemas"]["CostRow"][];
            /** Total Actual */
            total_actual: number | null;
            /** Total Budget */
            total_budget: number | null;
        };
        /** DefinitionOut */
        DefinitionOut: {
            /** Text */
            text: string;
            /** Unit */
            unit: string;
        };
        /** DocRow */
        DocRow: {
            /** Last Updated */
            last_updated: string | null;
            /** Page Id */
            page_id: string;
            /** Page Type */
            page_type: string | null;
            /** Space Key */
            space_key: string | null;
            /** Title */
            title: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Details
             * @default null
             */
            details: unknown | null;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
        };
        /** Evidence */
        Evidence: {
            /** Fact Key */
            fact_key: string;
            /** Value */
            value?: unknown;
        };
        /** FilterOption */
        FilterOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** FindingOut */
        FindingOut: {
            /** Body Md */
            body_md: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Finding Id */
            finding_id: string;
            /** Kind */
            kind: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "rule" | "ai";
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Run Id */
            run_id: string | null;
            /** Severity */
            severity: string | null;
            /** Status */
            status: string;
            /** Subject Id */
            subject_id: string | null;
            /** Subject Type */
            subject_type: string | null;
            /** System Detected */
            system_detected: boolean;
            /** Title */
            title: string;
        };
        /** FindingsOut */
        FindingsOut: {
            /** Items */
            items: components["schemas"]["FindingOut"][];
        };
        /** FlowRow */
        FlowRow: {
            /** Arrived */
            arrived: number;
            /** Closed */
            closed: number;
            /** Group */
            group: string | null;
            /** Period */
            period: string;
        };
        /** FreshnessRow */
        FreshnessRow: {
            /** Files */
            files: number | null;
            /** Last Import */
            last_import: string | null;
            /** Latest As Of */
            latest_as_of: string | null;
            /** Mapping Name */
            mapping_name: string;
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** ImportRow */
        ImportRow: {
            /** As Of */
            as_of: string | null;
            /** Batch Id */
            batch_id: number;
            /** Dq */
            dq: {
                [key: string]: unknown;
            };
            /** Dq Severity */
            dq_severity: string | null;
            /** File Name */
            file_name: string;
            /** Imported At */
            imported_at: string;
            /** Load Mode */
            load_mode: string;
            /** Mapping Name */
            mapping_name: string;
            /** Rows Inserted */
            rows_inserted: number;
            /** Rows Read */
            rows_read: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Rows Soft Deleted */
            rows_soft_deleted: number;
            /** Rows Unchanged */
            rows_unchanged: number;
            /** Rows Updated */
            rows_updated: number;
            /** Status */
            status: string;
        };
        /** ImportsOut */
        ImportsOut: {
            /** Items */
            items: components["schemas"]["ImportRow"][];
        };
        /** JiraRow */
        JiraRow: {
            /** Created */
            created: string | null;
            /** Issue Key */
            issue_key: string;
            /** Issue Type */
            issue_type: string | null;
            /** Priority */
            priority: string | null;
            /** Resolved */
            resolved: string | null;
            /** Status */
            status: string | null;
            /** Summary */
            summary: string | null;
        };
        /** Kpi */
        Kpi: {
            /** Compare */
            compare?: number | null;
            /** Definition */
            definition?: string | null;
            /** Delta */
            delta?: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | string | null;
        };
        /** LabelOut */
        LabelOut: {
            /** Am Category */
            am_category: string;
            /** Am Subcategory */
            am_subcategory: string | null;
            /** Confidence */
            confidence: number | null;
            /** Misfiled As */
            misfiled_as: string | null;
            /** Rationale */
            rationale: string | null;
            /** Run Id */
            run_id: string;
            /** Run Status */
            run_status: string | null;
            /** Stage */
            stage: string;
            /** Symptom Key */
            symptom_key: string | null;
        };
        /** LicenseRow */
        LicenseRow: {
            /** Active Qty 90D */
            active_qty_90d: number | null;
            /** App */
            app: string | null;
            /** Assigned Qty */
            assigned_qty: number | null;
            /** Assigned Ratio */
            assigned_ratio: number | null;
            /** Entitled Qty */
            entitled_qty: number | null;
            /** Idle Cost Base */
            idle_cost_base: number | null;
            /** License Id */
            license_id: string;
            /** Product */
            product: string | null;
            /** Unit Cost Base */
            unit_cost_base: number | null;
            /** Utilization */
            utilization: number | null;
            /** Vendor */
            vendor: string | null;
        };
        /** LicensesOut */
        LicensesOut: {
            /** As Of */
            as_of: string;
            /** Idle Cost Total */
            idle_cost_total: number;
            /** Items */
            items: components["schemas"]["LicenseRow"][];
        };
        /** MetaOut */
        MetaOut: {
            /** As Of Default */
            as_of_default: string | null;
            /** Base Currency */
            base_currency: string;
            /** Data Class */
            data_class: string;
            /** Definitions */
            definitions: {
                [key: string]: components["schemas"]["DefinitionOut"];
            };
            /** Entities */
            entities: {
                [key: string]: components["schemas"]["FilterOption"][];
            };
            /** Freshness */
            freshness: components["schemas"]["FreshnessRow"][];
            /** Modules */
            modules: components["schemas"]["ModuleRef"][];
            periods: components["schemas"]["PeriodsOut"];
            /** Pii Mode */
            pii_mode: string;
            /** Profile */
            profile: string;
            /** Reporting Tz */
            reporting_tz: string;
            /** Schema Version */
            schema_version: number;
            /** Sed Version */
            sed_version: string;
        };
        /** ModuleOut */
        ModuleOut: {
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Reports */
            reports: string[];
            /** Skills */
            skills: string[];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** ModuleRef */
        ModuleRef: {
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** ModulesOut */
        ModulesOut: {
            /** Modules */
            modules: components["schemas"]["ModuleOut"][];
        };
        /** MttrOut */
        MttrOut: {
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "week" | "month";
            /** Items */
            items: components["schemas"]["MttrRow"][];
        };
        /** MttrRow */
        MttrRow: {
            /** Count */
            count: number;
            /** Mean H */
            mean_h: number | null;
            /** Median H */
            median_h: number | null;
            /** P90 H */
            p90_h: number | null;
            /** Period */
            period: string;
        };
        /** NavItemOut */
        NavItemOut: {
            /** Icon */
            icon: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Module */
            module: string;
            /** Order */
            order: number;
            /** Path */
            path: string;
        };
        /** NavOut */
        NavOut: {
            /** Items */
            items: components["schemas"]["NavItemOut"][];
        };
        /** OpsAppOption */
        OpsAppOption: {
            /** App Id */
            app_id: string;
            /** Family */
            family: string | null;
            /** Name */
            name: string;
        };
        /** OpsFiltersOut */
        OpsFiltersOut: {
            /** Apps */
            apps: components["schemas"]["OpsAppOption"][];
            /** Families */
            families: string[];
        };
        /** OpsOverview */
        OpsOverview: {
            /** As Of */
            as_of: string;
            /** Attention Count */
            attention_count: number;
            /** Data As Of Last Import */
            data_as_of_last_import: string | null;
            /** Freshness */
            freshness: components["schemas"]["FreshnessRow"][];
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            /** Period */
            period: string;
            /** Review Queue Count */
            review_queue_count: number;
            /** Stale Open */
            stale_open: number;
            /** Top Risks */
            top_risks: components["schemas"]["FindingOut"][];
        };
        /** PeriodsOut */
        PeriodsOut: {
            /** Months */
            months: string[];
            /** Quarters */
            quarters: string[];
            /** Weeks */
            weeks: string[];
        };
        /** RenewalRow */
        RenewalRow: {
            /** Annual Value Base */
            annual_value_base: number | null;
            /** App */
            app: string | null;
            /** Auto Renew */
            auto_renew: boolean | null;
            /** Contract Id */
            contract_id: string;
            /** Contract Number */
            contract_number: string | null;
            /** Days To End */
            days_to_end: number | null;
            /** Days To Notice */
            days_to_notice: number | null;
            /** End Date */
            end_date: string | null;
            /** Notice Deadline */
            notice_deadline: string | null;
            /** Product */
            product: string | null;
            /** Renewal Status */
            renewal_status: string | null;
            /** Vendor */
            vendor: string | null;
        };
        /** RenewalsOut */
        RenewalsOut: {
            /** As Of */
            as_of: string;
            /** Days */
            days: number;
            /** Items */
            items: components["schemas"]["RenewalRow"][];
        };
        /** RunRow */
        RunRow: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Finished At */
            finished_at: string | null;
            /** Invoked Via */
            invoked_via: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Run Id */
            run_id: string;
            /** Sample Accuracy */
            sample_accuracy: number | null;
            /** Sample Ci High */
            sample_ci_high: number | null;
            /** Sample Ci Low */
            sample_ci_low: number | null;
            /** Sample N */
            sample_n: number | null;
            /** Skill */
            skill: string;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
        };
        /** RunsOut */
        RunsOut: {
            /** Items */
            items: components["schemas"]["RunRow"][];
        };
        /** SlaOut */
        SlaOut: {
            /** By Priority */
            by_priority: components["schemas"]["SlaPriorityRow"][];
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "week" | "month";
            /** Items */
            items: components["schemas"]["SlaRow"][];
            /** Sla Source */
            sla_source: string;
        };
        /** SlaPriorityRow */
        SlaPriorityRow: {
            /** Met */
            met: number;
            /** Pct */
            pct: number | null;
            /** Priority */
            priority: string;
            /** Total */
            total: number;
        };
        /** SlaRow */
        SlaRow: {
            /** Met */
            met: number;
            /** Pct */
            pct: number | null;
            /** Period */
            period: string;
            /** Total */
            total: number;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Am Category */
            am_category: string | null;
            /** Am Subcategory */
            am_subcategory: string | null;
            /** App Id */
            app_id: string | null;
            /** App Name */
            app_name: string | null;
            /** Assigned To Pid */
            assigned_to_pid: string | null;
            /** Assignment Group */
            assignment_group: string | null;
            /** Business Service Raw */
            business_service_raw: string | null;
            /** Caller Pid */
            caller_pid: string | null;
            /** Caused By */
            caused_by: string | null;
            /** Close Code */
            close_code: string | null;
            /** Close Notes */
            close_notes: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Cmdb Ci Raw */
            cmdb_ci_raw: string | null;
            /** Description */
            description: string | null;
            /** Is Open */
            is_open: boolean;
            /** Kind */
            kind: string;
            /** Label Confidence */
            label_confidence: number | null;
            /** Label Run Id */
            label_run_id: string | null;
            /** Labels */
            labels: components["schemas"]["LabelOut"][];
            /** Made Sla */
            made_sla: boolean | null;
            /** Number */
            number: string;
            /** Opened At */
            opened_at: string | null;
            /** Parent Incident */
            parent_incident: string | null;
            /** Priority */
            priority: number | null;
            /** Problem Id */
            problem_id: string | null;
            /** Reassignment Count */
            reassignment_count: number | null;
            /** Reopen Count */
            reopen_count: number | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Short Description */
            short_description: string | null;
            /** Sn Category */
            sn_category: string | null;
            /** Stale Open */
            stale_open: boolean;
            /** State */
            state: string | null;
            /** Sys Updated On */
            sys_updated_on: string | null;
            /** Ticket Id */
            ticket_id: string;
            /** Vendor Name */
            vendor_name: string | null;
        };
        /** TicketPage */
        TicketPage: {
            /** Items */
            items: components["schemas"]["TicketRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** TicketRow */
        TicketRow: {
            /** Am Category */
            am_category: string | null;
            /** Am Subcategory */
            am_subcategory: string | null;
            /** App Id */
            app_id: string | null;
            /** App Name */
            app_name: string | null;
            /** Assignment Group */
            assignment_group: string | null;
            /** Is Open */
            is_open: boolean;
            /** Kind */
            kind: string;
            /** Label Confidence */
            label_confidence: number | null;
            /** Label Run Id */
            label_run_id: string | null;
            /** Number */
            number: string;
            /** Opened At */
            opened_at: string | null;
            /** Priority */
            priority: number | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Short Description */
            short_description: string | null;
            /** Sn Category */
            sn_category: string | null;
            /** Stale Open */
            stale_open: boolean;
            /** State */
            state: string | null;
            /** Ticket Id */
            ticket_id: string;
            /** Vendor Name */
            vendor_name: string | null;
        };
        /** UnmappedList */
        UnmappedList: {
            /** Items */
            items: components["schemas"]["UnmappedRow"][];
        };
        /** UnmappedRow */
        UnmappedRow: {
            /** First Batch Id */
            first_batch_id: number | null;
            /** Kind */
            kind: string;
            /** Last Batch Id */
            last_batch_id: number | null;
            /** Occurrences */
            occurrences: number;
            /** Raw Value */
            raw_value: string;
            /** Score */
            score: number | null;
            /** Suggestion */
            suggestion: string | null;
        };
        /** VendorPoint */
        VendorPoint: {
            /** Mttr Median H */
            mttr_median_h: number | null;
            /** Period */
            period: string;
            /** Reassign Avg */
            reassign_avg: number | null;
            /** Sla Pct */
            sla_pct: number | null;
            /** Tickets */
            tickets: number;
        };
        /** VendorTrendRow */
        VendorTrendRow: {
            /** Delta Pp */
            delta_pp: number | null;
            /** Series */
            series: components["schemas"]["VendorPoint"][];
            /** Vendor */
            vendor: string;
            /** Vendor Id */
            vendor_id: string;
        };
        /** VendorTrendsOut */
        VendorTrendsOut: {
            /** Items */
            items: components["schemas"]["VendorTrendRow"][];
            /** Months */
            months: number;
        };
        /** VolumeRow */
        VolumeRow: {
            /** Net */
            net: number;
            /** Opened */
            opened: number;
            /** Period */
            period: string;
            /** Resolved */
            resolved: number;
        };
        /** VolumesOut */
        VolumesOut: {
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "week" | "month";
            /** Items */
            items: components["schemas"]["VolumeRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_alias_targets: {
        parameters: {
            query: {
                kind: string;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasTargetsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_create_alias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasOut"];
                };
            };
            /** @description Missing or invalid X-SED-Token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_dq_unmapped: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnmappedList"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_findings: {
        parameters: {
            query?: {
                kind?: string | null;
                origin?: ("rule" | "ai") | null;
                status?: "published" | "all";
                subject_type?: string | null;
                subject_id?: string | null;
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_imports: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_modules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulesOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_nav: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_apps: {
        parameters: {
            query?: {
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_app_360: {
        parameters: {
            query?: {
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App360Out"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_attention: {
        parameters: {
            query?: {
                limit?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_renewals: {
        parameters: {
            query?: {
                days?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewalsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_costs: {
        parameters: {
            query?: {
                group_by?: "app" | "vendor" | "category" | "app_category";
                months?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_filters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsFiltersOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_licenses: {
        parameters: {
            query?: {
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicensesOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_overview: {
        parameters: {
            query?: {
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOverview"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_tickets: {
        parameters: {
            query?: {
                /** @description Full-text search (scrubbed text only) */
                q?: string | null;
                kind?: string | null;
                priority?: number[];
                state?: string | null;
                open?: boolean | null;
                stale?: boolean | null;
                sn_category?: string | null;
                am_category?: string | null;
                sort?: "opened_desc" | "opened_asc" | "priority" | "updated_desc";
                page?: number;
                page_size?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_ticket_backlog: {
        parameters: {
            query?: {
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_ticket_mttr: {
        parameters: {
            query?: {
                granularity?: "week" | "month";
                n?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MttrOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_ticket_sla: {
        parameters: {
            query?: {
                granularity?: "week" | "month";
                n?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_ticket_volumes: {
        parameters: {
            query?: {
                granularity?: "week" | "month";
                n?: number;
                kind?: string;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumesOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_ticket_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ops_vendor_sla_trend: {
        parameters: {
            query?: {
                months?: number;
                /** @description app_id (repeatable) */
                app?: string[];
                family?: string | null;
                /** @description vendor_id */
                vendor?: string | null;
                /** @description assignment group */
                group?: string | null;
                /** @description 2026-W35, 2026-08 or 2026-Q3 */
                period?: string | null;
                /** @description YYYY-MM-DD (default: data as-of) */
                as_of?: string | null;
                /** @description Include unapproved AI content */
                include_drafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorTrendsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    core_runs: {
        parameters: {
            query?: {
                skill?: string | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsOut"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Database busy; retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
