"""Ops module (module #1): ITSM tickets, SLA, backlog, costs, licenses, vendors and the recurring ops reports.

Legacy locations still owned by this module (relocation is post-M2 backlog): sed/metrics.py, sed/analytics.py,
sed/synth/, sed/ingest/targets.py and the top-level `sed metrics | attention | analytics` commands.
"""

from __future__ import annotations

from sed.modules.contract import (
    AliasKind,
    ApiMount,
    CliMount,
    EntityRef,
    Module,
    NavItem,
    ReportDef,
    SkillDef,
    SynthDef,
)

MODULE = Module(
    key="ops",
    title="Application operations",
    description="ITSM tickets, SLA, backlog, costs, licenses, vendors and recurring ops reports",
    cli=(CliMount("ops", "sed.modules.ops.cli:app"),),
    legacy_cli=("metrics", "attention", "analytics"),
    api=ApiMount("sed.modules.ops.api:router"),
    nav=(
        NavItem("ops.overview", "Overview", "/ops", 10, "layout-dashboard"),
        NavItem("ops.attention", "Needs attention", "/ops/attention", 20, "alert-triangle"),
        NavItem("ops.tickets", "Tickets", "/ops/tickets", 30, "ticket"),
        NavItem("ops.apps", "App 360", "/ops/apps", 40, "apps"),
        NavItem("ops.costs", "Costs & Contracts", "/ops/costs", 50, "currency-euro"),
    ),
    reports=(
        ReportDef(
            "weekly",
            "Weekly Application Operations Review",
            "ops/reports/weekly.yaml",
            "sed.modules.ops.reports.weekly:build",
            ("week",),
            formats=("xlsx", "md", "pptx"),
            markdown="sed.reports.md_builder:render_weekly_md",
        ),
        ReportDef(
            "monthly",
            "Monthly Service Review",
            "ops/reports/monthly.yaml",
            "sed.modules.ops.reports.monthly:build",
            ("month",),
            formats=("xlsx", "md", "pptx"),
            markdown="sed.modules.ops.reports.markdown:render_monthly",
        ),
        ReportDef(
            "quarterly",
            "Quarterly Budget & Governance",
            "ops/reports/quarterly.yaml",
            "sed.modules.ops.reports.quarterly:build",
            ("quarter",),
            formats=("xlsx", "md", "pptx"),
            markdown="sed.modules.ops.reports.markdown:render_quarterly",
        ),
        ReportDef(
            "vendor",
            "Vendor Review",
            "ops/reports/vendor.yaml",
            "sed.modules.ops.reports.vendor:build",
            ("quarter", "month"),
            needs_vendor=True,
            formats=("xlsx", "md", "pptx"),
            markdown="sed.modules.ops.reports.markdown:render_vendor",
        ),
    ),
    skills=(
        SkillDef("sed-triage-batch", "sed.modules.ops.ai.triage:TriageBatchHandler", ("sed-analyze.js",)),
        SkillDef("sed-find-recurring", "sed.modules.ops.ai.recurring:RecurringHandler"),
        SkillDef("sed-assess-risks", "sed.modules.ops.ai.risks:RisksHandler"),
        SkillDef("sed-triage-open", "sed.modules.ops.ai.triage_open:TriageOpenHandler"),
        SkillDef("sed-draft-report", "sed.modules.ops.ai.draft_report:DraftReportHandler", ("sed-report.js",)),
    ),
    mappings_dir="ops/mappings",
    ingest_targets="sed.ingest.targets:TARGETS",
    ingest_hooks="sed.modules.ops.ingest_hooks:HOOKS",
    entities=(
        EntityRef("app", "application", "app_id", "name"),
        EntityRef("vendor", "vendor", "vendor_id", "name"),
        EntityRef("group", "assignment_group", "name", "name", validate_ids=False),
    ),
    alias_kinds=(
        AliasKind("app", "app"),
        AliasKind("vendor", "vendor"),
        AliasKind("group", "group"),
        AliasKind("ci", "app"),
        AliasKind("jira_project", "app"),
        AliasKind("jira_component", "app"),
        AliasKind("confluence_space", "app"),
    ),
    synth=SynthDef("sed.modules.ops.synth:generate"),
    metric_definitions="sed.modules.ops.definitions:DEFINITIONS",
    finding_kinds=(
        "issue_cluster",
        "renewal_risk",
        "license_risk",
        "vendor_risk",
        "cost_risk",
        "rationalization",
        "report_section",
    ),
    rule_findings="sed.analytics:compute_rule_findings",
    doctor_checks="sed.modules.ops.doctor:checks",
    extension_points=("triage",),  # sed.modules.ops.ai.extensions: subcategories and context for other modules' tickets
    config_files=(
        "ops/taxonomy.yaml",
        "ops/sla.yaml",
        "ops/risk_rules.yaml",
        "ops/vendor_groups.yaml",
        "ops/reports/weekly.yaml",
        "ops/reports/monthly.yaml",
        "ops/reports/quarterly.yaml",
        "ops/reports/vendor.yaml",
    ),
    data_subdirs=("config/ops", "config/ops/mappings", "config/ops/reports"),
    tables=(
        "assignment_group",
        "contract",
        "license",
        "license_usage",
        "cost_line",
        "ticket",
        "ticket_fts",
        "task_sla",
        "ci_rel",
        "ai_claim",
        "ai_ticket_label",
        "symptom_key_alias",
        "ai_cluster_member",
        "v_ticket",
        "v_label_current",
    ),
    owned_paths=(
        "src/sed/modules/ops/**",
        "src/sed/metrics.py",
        "src/sed/analytics.py",
        "src/sed/ingest/targets.py",
        "src/sed/synth/**",
        "config/ops/**",
        ".claude/skills/sed-triage-batch/**",
        ".claude/skills/sed-find-recurring/**",
        ".claude/skills/sed-assess-risks/**",
        ".claude/skills/sed-triage-open/**",
        ".claude/skills/sed-draft-report/**",
        ".claude/workflows/sed-analyze.js",
        ".claude/workflows/sed-report.js",
        "web/src/modules/ops/**",
        "tests/modules/ops/**",
    ),
)
