"""Ticket text templates with ground-truth labels (app-owner taxonomy + symptom key).

Placeholders: {app}, {ci}, {n} (a number), {doc} (document id), {site}, {queue}, {report}, {module}.
Each template has English phrasings and, for some, French ones (~10% of tickets use French).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Symptom:
    key: str
    am_category: str
    am_subcategory: str
    sn_category: str
    sn_subcategory: str
    short_en: tuple[str, ...]
    short_fr: tuple[str, ...] = ()
    desc: tuple[str, ...] = ()
    close: tuple[str, ...] = ("Issue resolved and confirmed with the user.",)
    weight: float = 1.0
    families: tuple[str, ...] = field(default_factory=tuple)


SYMPTOMS: list[Symptom] = [
    Symptom(
        "login-failure",
        "access",
        "login_failure",
        "Software",
        "Access",
        ("Cannot log in to {app}", "{app} login fails with error {n}", "Unable to sign in to {app}"),
        ("Impossible de se connecter à {app}",),
        (
            "User reports the login page of {app} returns error code {n} after entering credentials.",
            "Since this morning the {app} sign-in fails for several users on site {site}.",
        ),
        ("Cache cleared and session reset; login works again.", "Account unlocked, user can log in."),
        2.2,
    ),
    Symptom(
        "account-locked",
        "access",
        "account_locked",
        "Software",
        "Access",
        ("Account locked in {app}", "{app} account locked after password attempts"),
        ("Compte bloqué dans {app}",),
        ("User account is locked out of {app} after several failed attempts.",),
        ("Account unlocked.",),
        1.4,
    ),
    Symptom(
        "missing-authorization",
        "access",
        "authorization",
        "Software",
        "Authorization",
        (
            "No authorization for transaction in {app}",
            "Missing role to approve in {app}",
            "Access denied to {module} module in {app}",
        ),
        ("Pas d'autorisation pour {module} dans {app}",),
        ("User needs the approver role for {module} but gets 'access denied' in {app}.",),
        ("Role assigned after manager approval.",),
        1.6,
    ),
    Symptom(
        "sso-redirect-loop",
        "access",
        "sso",
        "Software",
        "Single sign-on",
        ("SSO redirect loop when opening {app}", "{app} keeps redirecting to the SSO page"),
        (),
        ("Opening {app} loops between the identity provider and the application.",),
        ("Stale cookie removed; SSO works.",),
        0.6,
    ),
    Symptom(
        "interface-message-failure",
        "integration",
        "message_failure",
        "Software",
        "Interface",
        ("Interface messages stuck in queue {queue} for {app}", "{app} outbound IDocs in error"),
        ("Messages bloqués dans la file {queue} ({app})",),
        ("{n} messages are stuck in queue {queue}; downstream system has not received updates.",),
        ("Queue restarted, messages reprocessed.",),
        1.3,
    ),
    Symptom(
        "file-transfer-failed",
        "integration",
        "file_transfer",
        "Software",
        "Interface",
        ("SFTP transfer failed for {app}", "Daily file from {app} not received by partner"),
        (),
        ("The scheduled file transfer from {app} to the partner failed with a connection timeout.",),
        ("Credentials renewed on SFTP endpoint; transfer re-run.",),
        0.9,
    ),
    Symptom(
        "api-error-500",
        "integration",
        "api_error",
        "Software",
        "Interface",
        ("{app} API returns HTTP 500", "Integration call to {app} fails with 500"),
        (),
        ("Calls to the {app} REST API fail intermittently with HTTP 500 since {n}:00.",),
        ("Backend pod restarted; error rate back to normal.",),
        0.9,
    ),
    Symptom(
        "slow-screen",
        "performance",
        "slow_ui",
        "Software",
        "Performance",
        ("{app} very slow", "{app} screens take minutes to load", "Performance issue in {app} {module}"),
        ("{app} très lent",),
        ("Users on site {site} report {app} pages taking more than {n} seconds to load.",),
        ("Database statistics refreshed; response time normal.",),
        1.8,
    ),
    Symptom(
        "report-timeout",
        "performance",
        "timeout",
        "Software",
        "Performance",
        ("Report {report} times out in {app}", "{app} report {report} never finishes"),
        (),
        ("Running report {report} in {app} ends with a timeout after {n} minutes.",),
        ("Report query optimised and index added.",),
        1.0,
    ),
    Symptom(
        "missing-master-data",
        "data_quality",
        "master_data",
        "Software",
        "Data",
        ("Material master missing in {app}", "Supplier not found in {app}", "Customer record missing in {app}"),
        ("Donnée de base manquante dans {app}",),
        ("Record {doc} cannot be found in {app} although it exists in the source system.",),
        ("Master data replicated manually.",),
        1.2,
    ),
    Symptom(
        "wrong-amounts",
        "data_quality",
        "wrong_data",
        "Software",
        "Data",
        ("Wrong amounts displayed in {app}", "{app} shows incorrect totals on {doc}"),
        (),
        ("Document {doc} in {app} shows totals that do not match the source lines.",),
        ("Recalculation job executed; totals corrected.",),
        1.0,
    ),
    Symptom(
        "duplicate-records",
        "data_quality",
        "duplicate_data",
        "Software",
        "Data",
        ("Duplicate records in {app}", "{app} created duplicate entries for {doc}"),
        (),
        ("Two identical entries were created in {app} for {doc}.",),
        ("Duplicate removed; root cause under review.",),
        0.8,
    ),
    Symptom(
        "batch-job-failed",
        "batch_job",
        "job_failure",
        "Software",
        "Batch",
        ("Nightly job failed in {app}", "Batch job {n} aborted in {app}"),
        ("Le job de nuit a échoué dans {app}",),
        ("Scheduled job {n} in {app} ended with status 'aborted' at {n}:15.",),
        ("Job restarted successfully.",),
        1.2,
    ),
    Symptom(
        "report-not-generated",
        "batch_job",
        "report_generation",
        "Software",
        "Batch",
        ("Scheduled report {report} not generated", "{app} did not send the daily report"),
        (),
        ("The scheduled report {report} from {app} was not delivered this morning.",),
        ("Scheduler service restarted; report sent.",),
        0.9,
    ),
    Symptom(
        "button-does-nothing",
        "defect",
        "functional_bug",
        "Software",
        "Defect",
        ("Save button does nothing in {app}", "{app} error when submitting form", "Unexpected error in {app} {module}"),
        ("Erreur inattendue dans {app}",),
        ("Clicking save in {module} shows no reaction; browser console shows a script error.",),
        ("Fixed by hotfix {n}.",),
        1.4,
    ),
    Symptom(
        "regression-after-release",
        "defect",
        "regression",
        "Software",
        "Defect",
        ("{app} feature broken after release", "Regression in {app} since last update"),
        (),
        ("After the latest release of {app}, the {module} function no longer calculates correctly.",),
        ("Rolled back faulty component; fix planned.",),
        0.8,
    ),
    Symptom(
        "layout-broken",
        "defect",
        "ui_bug",
        "Software",
        "Defect",
        ("{app} page layout broken", "Text overlaps in {app} screen"),
        (),
        ("The {module} screen in {app} renders incorrectly in the browser.",),
        ("CSS fix deployed.",),
        0.5,
    ),
    Symptom(
        "how-to-export",
        "how_to",
        "usage_question",
        "Inquiry / Help",
        "How to",
        ("How to export data from {app}", "Question: export to Excel in {app}", "How do I run report {report}"),
        ("Comment exporter depuis {app}",),
        ("User asks how to export the {module} list from {app} to Excel.",),
        ("Explained the export function; user satisfied.",),
        1.3,
    ),
    Symptom(
        "training-request",
        "how_to",
        "training",
        "Inquiry / Help",
        "Training",
        ("Need training on {app}", "New joiner needs {app} walkthrough"),
        (),
        ("New team member needs an introduction to {app} {module}.",),
        ("Training material shared.",),
        0.6,
    ),
    Symptom(
        "server-down",
        "infrastructure",
        "server",
        "Hardware",
        "Server",
        ("{ci} not responding", "Server {ci} down"),
        (),
        ("Monitoring reports {ci} unreachable since {n}:05.",),
        ("VM restarted by hosting team.",),
        0.7,
    ),
    Symptom(
        "certificate-expired",
        "infrastructure",
        "certificate",
        "Software",
        "Certificate",
        ("Certificate expired on {app}", "SSL warning when opening {app}"),
        (),
        ("Browser shows certificate expired for the {app} URL.",),
        ("Certificate renewed.",),
        0.4,
    ),
    Symptom(
        "disk-full",
        "infrastructure",
        "storage",
        "Hardware",
        "Storage",
        ("Disk full on {ci}", "Low disk space alert {ci}"),
        (),
        ("Filesystem on {ci} is at {n}% usage.",),
        ("Logs purged; disk extended.",),
        0.5,
    ),
    Symptom(
        "network-drop",
        "infrastructure",
        "network",
        "Network",
        "Connectivity",
        ("{app} disconnects on site {site}", "Network drops when using {app}"),
        (),
        ("Users on site {site} lose the connection to {app} every few minutes.",),
        ("Switch port replaced.",),
        0.5,
    ),
    Symptom(
        "printing-issue",
        "other",
        "other",
        "Hardware",
        "Printer",
        ("Cannot print from {app}", "Labels do not print in {app}"),
        ("Impossible d'imprimer depuis {app}",),
        ("Printing from {app} to the site {site} printer fails.",),
        ("Printer driver reinstalled.",),
        0.7,
    ),
]

# --- planted-pattern templates ------------------------------------------------------------------------------

P1_INTERFACE_TIMEOUT = Symptom(
    "interface-posting-timeout",
    "integration",
    "interface_timeout",
    "Software",
    "Interface",
    (
        "Posting to ledger times out in Orion ERP",
        "Orion ERP interface timeout when posting invoices",
        "Invoice posting hangs - timeout from GL interface",
        "GL posting fails with timeout (Orion ERP)",
    ),
    ("Timeout lors de la comptabilisation dans Orion ERP",),
    ("Posting of invoice batch {doc} to the general ledger interface times out after {n} seconds.",),
    ("Interface timeout parameter restored; postings reprocessed.",),
)
P5_BATCH_FAILURE = Symptom(
    "month-start-batch-failure",
    "batch_job",
    "job_failure",
    "Software",
    "Batch",
    (
        "Ledgerline month opening batch failed",
        "Period open job failed in Ledgerline Finance",
        "Ledgerline Finance: accrual batch aborted",
    ),
    ("Échec du batch d'ouverture de période Ledgerline",),
    ("The period opening batch in Ledgerline Finance aborted with a lock timeout on business day {n}.",),
    ("Batch restarted manually after lock released.",),
)
P6_ACCESS_REQUEST = Symptom(
    "password-reset-request",
    "access",
    "password_reset",
    "Inquiry / Help",
    "Password",
    (
        "Please reset my password for {app}",
        "Forgot password {app}",
        "Need access to {app}",
        "Request access to {app} for new colleague",
    ),
    ("Merci de réinitialiser mon mot de passe {app}",),
    ("User requests a password reset / new access for {app}. No system error involved.",),
    ("Password reset done.", "Access granted."),
)
P7_SSO_OUTAGE = Symptom(
    "sso-outage",
    "access",
    "sso",
    "Software",
    "Single sign-on",
    ("Cannot log in to {app} - SSO error", "{app}: identity provider unavailable", "SSO login broken for {app}"),
    ("Erreur SSO sur {app}",),
    ("All users receive 'identity provider unavailable' when opening {app}.",),
    ("Resolved by parent incident: identity provider certificate renewed.",),
)
GO_LIVE_HOWTO = Symptom(
    "new-app-onboarding-question",
    "how_to",
    "usage_question",
    "Inquiry / Help",
    "How to",
    ("Where do I find my courses in {app}", "How to enrol in {app}", "{app} question after go-live"),
    (),
    ("User is new to {app} after the go-live and asks where to find the {module} page.",),
    ("Explained navigation.",),
)

REQUEST_ITEMS = [
    ("New user account", "Account request for {app}"),
    ("Access request", "Access to {app} {module}"),
    ("Software installation", "Install {app} client"),
    ("Role change", "Change role in {app}"),
    ("Report subscription", "Subscribe to report {report}"),
    ("Mailbox or distribution list", "Add user to distribution list"),
    ("Data extract", "Data extract from {app}"),
]

CHANGE_TEXTS = [
    "Deploy release {n} of {app}",
    "Patch {ci} operating system",
    "Update interface configuration for {app}",
    "Database maintenance on {ci}",
    "Renew certificate for {app}",
    "Scale out {app} application servers",
]

PROBLEM_TEXTS = [
    "Recurring performance degradation in {app}",
    "Intermittent login failures in {app}",
    "Repeated batch job failures in {app}",
    "Frequent interface errors between {app} and downstream systems",
]

MODULES = [
    "Invoices",
    "Purchase Orders",
    "Approvals",
    "Timesheets",
    "Dashboard",
    "Inventory",
    "Quotes",
    "Recipes",
    "Work Orders",
    "Payroll",
    "Assets",
    "Contracts",
    "Courses",
    "Reports",
]
SITES = ["Lyon", "Grenoble", "Barcelona", "Monterrey", "Bangalore", "Nashville", "Wuhan", "Budapest", "Dublin", "Rueil"]
REPORTS = [
    "Aged Debtors",
    "Stock Valuation",
    "Open Orders",
    "Headcount",
    "OEE Daily",
    "Pipeline Weekly",
    "Cost Center Actuals",
]
QUEUES = ["OUTBOUND.GL", "EDI.ORDERS", "SYNC.MASTER", "PAYMENTS.OUT"]
CLOSE_CODES = [
    "Solved (Permanently)",
    "Solved (Work Around)",
    "Solved Remotely (Permanently)",
    "Not Solved (Not Reproducible)",
    "Closed/Resolved by Caller",
]
SN_GENERIC_CATEGORY = ("Inquiry / Help", "Other")
