"""`sed schedule write`: the weekly automation as files in DATA_DIR/automation (never in the repo, never registered
by SED).

`weekly.ps1` pulls every enabled connector, imports the inbox, refreshes rule findings and, with `--analyze`, runs the
sed-analyze workflow headless through `claude -p`. Unattended runs never approve anything: drafts wait for review.
`weekly-task.xml` is a Task Scheduler definition (weekly trigger, run only when the user is logged on, so Claude Code
sign-in and the salt file are available). The user registers it with the printed `schtasks` command.
"""

from __future__ import annotations

import getpass
import re
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from sed.errors import ValidationFailed
from sed.paths import Paths, repo_root

DAYS = {"MON": "Monday", "TUE": "Tuesday", "WED": "Wednesday", "THU": "Thursday", "FRI": "Friday", "SAT": "Saturday",
        "SUN": "Sunday"}  # fmt: skip
TASK_NAME = "SED weekly"


def _ps(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def script_text(paths: Paths, *, connectors: list[str], analyze: bool, cli: str = "uv run sed") -> str:
    profile = paths.profile
    lines = [
        "# SED weekly automation, generated by `sed schedule write`. Runs as the logged-on user; approves nothing.",
        "$ErrorActionPreference = 'Continue'",
        f"Set-Location -LiteralPath {_ps(str(repo_root()))}",
        "$env:UV_NO_SYNC = '1'",
        "$env:PYTHONUTF8 = '1'",
        f"$logDir = {_ps(str(paths.data_dir / 'logs'))}",
        "New-Item -ItemType Directory -Force -Path $logDir | Out-Null",
        "$log = Join-Path $logDir ('automation-' + (Get-Date -Format 'yyyyMMdd-HHmm') + '.log')",
        "function Step($name, [scriptblock]$block) {",
        "  Add-Content -LiteralPath $log -Value ('== ' + (Get-Date -Format s) + ' ' + $name)",
        "  & $block *>> $log",
        "  Add-Content -LiteralPath $log -Value ('exit ' + $LASTEXITCODE)",
        "}",
    ]
    for connector in connectors:
        lines.append(f"Step 'pull {connector}' {{ {cli} pull {connector} --profile {profile} --json }}")
    lines += [
        f"Step 'import' {{ {cli} import --inbox --profile {profile} --json }}",
        f"Step 'rule findings' {{ {cli} analytics refresh --profile {profile} --json }}",
    ]
    if analyze:
        args = '{\\"profile\\": \\"' + profile + '\\", \\"steps\\": [\\"triage\\", \\"recurring\\", \\"risks\\"]}'
        prompt = f"Run the sed-analyze workflow with args {args}. Do not approve or reject anything."
        lines.append(f"Step 'analyze' {{ claude -p \"{prompt}\" --output-format json }}")
    lines.append("Add-Content -LiteralPath $log -Value ('== done ' + (Get-Date -Format s))")
    return "\r\n".join(lines) + "\r\n"


def task_xml(script: Path, *, day: str, time: str, user: str) -> str:
    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>SED weekly: pull, import, rule findings and AI drafts (approves nothing)</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2026-01-05T{time}:00</StartBoundary>
      <ScheduleByWeek>
        <DaysOfWeek><{DAYS[day]} /></DaysOfWeek>
        <WeeksInterval>1</WeeksInterval>
      </ScheduleByWeek>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>{escape(user)}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <StartWhenAvailable>true</StartWhenAvailable>
    <ExecutionTimeLimit>PT6H</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>-NoProfile -ExecutionPolicy Bypass -File "{escape(str(script))}"</Arguments>
    </Exec>
  </Actions>
</Task>
"""


def write_schedule(paths: Paths, *, day: str, time: str, analyze: bool) -> dict[str, Any]:
    from sed.connectors.config import CONNECTORS, load_config

    day = day.upper()
    if day not in DAYS:
        raise ValidationFailed(f"--day must be one of {', '.join(DAYS)}")
    if not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", time):
        raise ValidationFailed("--time must be HH:MM (24 h)")
    config = load_config(paths)
    connectors = [name for name in CONNECTORS if (cfg := getattr(config, name)) is not None and cfg.enabled]
    folder = paths.data_dir / "automation"
    folder.mkdir(parents=True, exist_ok=True)
    script = folder / "weekly.ps1"
    xml = folder / "weekly-task.xml"
    script.write_bytes(script_text(paths, connectors=connectors, analyze=analyze).encode("utf-8-sig"))
    xml.write_text(task_xml(script, day=day, time=time, user=getpass.getuser()), encoding="utf-16")
    return {
        "profile": paths.profile,
        "script": script.as_posix(),
        "task_xml": xml.as_posix(),
        "connectors": connectors,
        "analyze": analyze,
        "schedule": f"every {DAYS[day]} at {time} (only while you are logged on)",
        "register": f'schtasks /Create /TN "{TASK_NAME}" /XML "{xml}"',
        "remove": f'schtasks /Delete /TN "{TASK_NAME}" /F',
        "note": "SED does not register the task: run the register command yourself after reading the script.",
    }
